trigger:
  branches:
    include:
      - main

variables:
  imageName: 'spring-petclinic'
  dockerHubId: '<michaelstev25>'

pool:
  vmImage: 'default'

steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean install'
    displayName: 'Build with Maven'

  - task: Docker@2
    inputs:
      containerRegistry: '<docker-service-connection>'
      repository: '$(dockerHubId)/$(imageName)'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: |
        latest
    displayName: 'Build and Push Docker Image'

  - task: SSH@0
    inputs:
      sshEndpoint: 'AzureVM-SSH'
      runOptions: 'commands'
      commands: |
        docker pull $(dockerHubId)/$(imageName):latest
        docker stop petclinic || true && docker rm petclinic || true
        docker run -d -p 8080:8080 --name petclinic $(dockerHubId)/$(imageName):latest
    displayName: 'Deploy on Azure VM'

